# Shadowrocket
# https://github.com/aydar-sharifulin/podkop-rules
# Public reference configuration

[General]
ipv6 = false
prefer-ipv6 = false

private-ip-answer = true

dns-direct-system = false
dns-fallback-system = false
dns-direct-fallback-proxy = true

dns-server = https://security.cloudflare-dns.com/dns-query,https://dns.google/dns-query
fallback-dns-server = system

hijack-dns = :53

skip-proxy = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local,captive.apple.com

tun-excluded-routes = 10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.168.0.0/16

[Rule]

# Advertisement & malware
RULE-SET,https://github.com/aydar-sharifulin/podkop-rules/releases/download/latest/oisd_small.list,REJECT

# Explicit proxy exceptions
RULE-SET,https://github.com/aydar-sharifulin/podkop-rules/releases/download/latest/proxy-from-direct.list,PROXY

# IP detection services
RULE-SET,https://github.com/aydar-sharifulin/podkop-rules/releases/download/latest/ip-checkers.list,DIRECT

# Russian & trusted services
RULE-SET,https://github.com/aydar-sharifulin/podkop-rules/releases/download/latest/ru-direct.list,DIRECT

FINAL,PROXY
